### Mathematical Tools in NumPy

In [1]:
import numpy as np

In [2]:
a = np.array(['a', 'b', 'c', 'd', 'e'])
a

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [3]:
np.random.permutation(a)

array(['c', 'b', 'e', 'a', 'd'], dtype='<U1')

In [4]:
a

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [5]:
np.random.shuffle(a)
a

array(['d', 'b', 'a', 'c', 'e'], dtype='<U1')

### Math operations

In [6]:
b = np.array([1, 2, 3, 4, 5])
b

array([1, 2, 3, 4, 5])

In [7]:
c = np.array([2, 2, 2, 2, 2])
c

array([2, 2, 2, 2, 2])

In [8]:
newarr = result = np.add(b, c)
newarr

array([3, 4, 5, 6, 7])

In [9]:
result_div = np.divide(b, c)
result_div

array([0.5, 1. , 1.5, 2. , 2.5])

In [10]:
result_divmod = np.divmod(b, c)
result_divmod

(array([0, 1, 1, 2, 2]), array([1, 0, 1, 0, 1]))

### Summations

In [11]:
a = np.array([1, 2, 3])
b= np.array([1, 2, 3])
x = np.array([1, 1, 1])

In [15]:
c = np.sum([a, b, x], axis = 1)
c

array([6, 6, 3])

In [17]:
d = np.sum([a, b, x], axis = 0)
d


array([3, 5, 7])

In [18]:
a_cum1 = np.cumsum(a)
a_cum1

array([1, 3, 6])

In [19]:
x_cum1 = np.cumsum(x)
x_cum1

array([1, 2, 3])

In [20]:
a_cprod = np.cumprod(a)
a_cprod

array([1, 2, 6])

In [21]:
a_prod = np.prod([a, b], axis = 1)
a_prod

array([6, 6])

In [22]:
a_prod2 = np.prod([a, b], axis = 0)
a_prod2

array([1, 4, 9])

### Differences

In [23]:
a_diff = np.diff(a)
a_diff

array([1, 1])

In [24]:
x_diff = np.diff(x)
x_diff

array([0, 0])

In [25]:
w= np.array([10, 5, 20, 3])

w_diff = np.diff(w)
w_diff

array([ -5,  15, -17])

In [26]:
w_diff_3 = np.diff(w, n=3)
w_diff_3

array([-52])