In [1]:
import numpy as np

2.B.1 Using loops w arrays

In [ ]:
array1d = np.array

In [113]:
arr3d = np.array([[[8,7], [6,5]],[[4, 3],[2,1]]])

for i in arr3d:
    print(i)

[[8 7]
 [6 5]]
[[4 3]
 [2 1]]


joinging arrays with concatenate()

In [5]:
arr_a = np.array([1,2,3])
arr_b = np.array([11,12,13])

In [6]:
arr_c = np.concatenate((arr_a, arr_b))
arr_c

array([ 1,  2,  3, 11, 12, 13])

In [8]:
arr_d = np.concatenate((arr_a,arr_b), axis = 0)
arr_d

array([ 1,  2,  3, 11, 12, 13])

In [9]:
arr_stacked = np.stack((arr_a,arr_b), axis = 1)
arr_stacked

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [10]:
stack_of_stacks = np.concatenate((arr_stacked, arr_stacked))
stack_of_stacks

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [11]:
stack_of_stacks2 = np.concatenate((arr_stacked,arr_stacked), axis = 1)
stack_of_stacks2

array([[ 1, 11,  1, 11],
       [ 2, 12,  2, 12],
       [ 3, 13,  3, 13]])

In [13]:
ex_vstack = np.vstack((arr_stacked,arr_stacked))
ex_vstack

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [14]:
ex_hstack = np.hstack((arr_stacked,arr_stacked))
ex_hstack

array([[ 1, 11,  1, 11],
       [ 2, 12,  2, 12],
       [ 3, 13,  3, 13]])

In [16]:
ex_dstack = np.dstack((arr_stacked, arr_stacked))
ex_dstack

array([[[ 1,  1],
        [11, 11]],

       [[ 2,  2],
        [12, 12]],

       [[ 3,  3],
        [13, 13]]])

2.B.5 Splitting arrays

In [17]:
ex_vstack

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [20]:
split_3ways = np.array_split(ex_vstack, 3)
split_3ways

[array([[ 1, 11],
        [ 2, 12]]),
 array([[ 3, 13],
        [ 1, 11]]),
 array([[ 2, 12],
        [ 3, 13]])]

In [21]:
split_4ways = np.array_split(ex_vstack, 4)
split_4ways

[array([[ 1, 11],
        [ 2, 12]]),
 array([[ 3, 13],
        [ 1, 11]]),
 array([[ 2, 12]]),
 array([[ 3, 13]])]

In [22]:
split_4_1 = np.array_split(ex_vstack, 4, axis = 1)
split_4_1

[array([[1],
        [2],
        [3],
        [1],
        [2],
        [3]]),
 array([[11],
        [12],
        [13],
        [11],
        [12],
        [13]]),
 array([], shape=(6, 0), dtype=int64),
 array([], shape=(6, 0), dtype=int64)]

### 2.B.6 Using where() to search and alter arrays

In [24]:
values = np.array([4,9,4,8,0,6])
cond1 = np.where(values < 5)
cond1

(array([0, 2, 4]),)

In [25]:
print(np.array(cond1))

[[0 2 4]]


In [26]:
print(cond1)

(array([0, 2, 4]),)


In [27]:
cond2 = np.where(values < 5, values, values * .9)
print(cond2)

[4.  8.1 4.  7.2 0.  5.4]


In [28]:
cond2

array([4. , 8.1, 4. , 7.2, 0. , 5.4])

In [29]:
cond3 = np.where(values < 5, values, 'over 5')
print(cond3)

['4' 'over 5' '4' 'over 5' '0' 'over 5']


In [30]:
ex_vstack

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [31]:
cond4 = np.where(ex_vstack % 2)
cond4

(array([0, 0, 2, 2, 3, 3, 5, 5]), array([0, 1, 0, 1, 0, 1, 0, 1]))

In [33]:
cond5 = np.where(ex_vstack > 10, ex_vstack, 'down')
print(cond5)

[['down' '11']
 ['down' '12']
 ['down' '13']
 ['down' '11']
 ['down' '12']
 ['down' '13']]


### 2.B.7 Sorting arrays

In [34]:
values

array([4, 9, 4, 8, 0, 6])

In [35]:
print(np.sort(values))

[0 4 4 6 8 9]


In [36]:
print(np.sort(ex_vstack))

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 1 11]
 [ 2 12]
 [ 3 13]]


In [37]:
print(np.sort(cond5))

[['11' 'down']
 ['12' 'down']
 ['13' 'down']
 ['11' 'down']
 ['12' 'down']
 ['13' 'down']]


In [38]:
arr_a = np.array([7,5,3])
arr_b = np.array([11,9,7])
ab =np.hstack((arr_a, arr_b))
ab

array([ 7,  5,  3, 11,  9,  7])

In [39]:
ab2 = np.vstack((arr_a, arr_b))
ab2

array([[ 7,  5,  3],
       [11,  9,  7]])

In [40]:
ab3 = np.dstack((arr_a, arr_b))
ab3

array([[[ 7, 11],
        [ 5,  9],
        [ 3,  7]]])

In [41]:
print(np.sort(ab))

[ 3  5  7  7  9 11]


In [42]:
print(np.sort(ab2))

[[ 3  5  7]
 [ 7  9 11]]


In [43]:
print(np.sort(ab3))

[[[ 7 11]
  [ 5  9]
  [ 3  7]]]


### 2.B.8 Filtering arrays

In [44]:
z = np.array([14, 9, 4, 18, 0, 6])
z

array([14,  9,  4, 18,  0,  6])

In [46]:
#to create a boolean index using standard Python 

filter_z = []

for i in z:
    if i > 10:
        filter_z.append(True)
    else:
        filter_z.append(False)

print(filter_z)

[True, False, False, True, False, False]


In [47]:
#applying boolean index

y = z[filter_z]
print(y)

[14 18]


In [48]:
z

array([14,  9,  4, 18,  0,  6])

In [49]:
x = z > 10
z_over_10 = z[x]
print(z_over_10)

[14 18]


### 2.C Random in Numpy

In [55]:
#Array of random integers

h = np.random.randint(1, 200, size =(3, 4, 2))
h

array([[[ 92,  11],
        [173,  32],
        [ 13, 183],
        [105, 192]],

       [[172, 161],
        [109,  47],
        [ 46, 169],
        [130, 197]],

       [[155,  86],
        [ 14, 112],
        [ 56,  46],
        [182, 116]]], dtype=int32)

In [54]:
# Array of random floats (btwn 0 and 1)

j = np.random.rand(3, 4, 2)
j

array([[[0.80497789, 0.21411584],
        [0.48353529, 0.61664652],
        [0.42449435, 0.11567707],
        [0.83457088, 0.63856735]],

       [[0.326627  , 0.67296534],
        [0.09651153, 0.22620302],
        [0.18887271, 0.30905383],
        [0.04303728, 0.18467366]],

       [[0.58863666, 0.43323784],
        [0.54141197, 0.68299702],
        [0.92859312, 0.64189598],
        [0.82364986, 0.17271139]]])

In [56]:
z 

array([14,  9,  4, 18,  0,  6])

In [57]:
h

array([[[ 92,  11],
        [173,  32],
        [ 13, 183],
        [105, 192]],

       [[172, 161],
        [109,  47],
        [ 46, 169],
        [130, 197]],

       [[155,  86],
        [ 14, 112],
        [ 56,  46],
        [182, 116]]], dtype=int32)

In [66]:
choice_z = np.random.choice(z, size = (3,2))
choice_z

array([[ 9, 14],
       [14, 14],
       [ 9, 18]])

In [100]:
choice_k = np.random.choice([3,5,7,9,11,13], size = (1))
choice_k

array([11])

In [109]:
# Random distribution using probabilitiy density

choice_m = np.random.choice([3, 5, 7, 9, 11, 13], p = [.1, .1, .1, .1, .2, .4], size = (3, 2))
choice_m

array([[13, 11],
       [13, 11],
       [ 3, 11]])

### 2.C.5 Normal Distribution

In [112]:
x_normal = np.random.normal(loc=5, scale=2, size=(30,2,3))
x_normal

array([[[ 5.99411672,  5.83217655,  5.09669452],
        [ 4.41978771,  8.69836334,  7.34769863]],

       [[ 6.3925176 ,  6.50432321,  5.84654942],
        [ 1.63922746,  3.8339594 ,  1.7484058 ]],

       [[ 3.42774036,  3.15979339,  3.09148597],
        [ 4.93942301,  5.93380519,  3.79034957]],

       [[-0.29108677,  5.77002071,  3.93201789],
        [ 5.77057883,  4.38826726,  4.88309737]],

       [[11.42605082,  4.56900283,  6.09641295],
        [ 6.01807157,  4.54160846,  0.88992232]],

       [[ 6.28289777,  5.58033721,  4.14395627],
        [ 5.05823329,  3.39133954,  7.20505512]],

       [[ 5.35637204,  5.73588994,  3.94379355],
        [ 7.76095841,  1.34775642,  3.77257917]],

       [[ 5.45473762,  6.40917285,  3.96201224],
        [ 7.36674912,  6.9131929 ,  4.59483994]],

       [[ 6.70480365,  1.85715774,  6.0680418 ],
        [ 7.97247792,  1.85856571,  5.76670886]],

       [[ 4.21702629,  8.61989515,  2.5255029 ],
        [ 6.88532689,  4.91912949,  1.55345486]],

