In [1]:
import numpy as np

### Looping Through Arrays

In [2]:
arrA = np.array([[11,12,13], [13,15,16]])
print(arrA)

[[11 12 13]
 [13 15 16]]


In [3]:
for x in arrA:
    print(x*2)

[22 24 26]
[26 30 32]


In [4]:
for x in arrA:
    for y in (x):
        print(y *2) 

22
24
26
26
30
32


Because it is a 2 demensional array, the first loop breaks the array into two, 1 demensional sub arrays. From there, if we enter a nested loop, we are able to return the individual values with the array. 

In [6]:

for x in arrA:
    for y in x:
        loop_result = (y*2)
        print(loop_result)

22
24
26
26
30
32


### Joining and Stacking Arrays

In [7]:
joined_array_1 = np.concatenate((arrA, arrA), axis = 0)
print(joined_array_1)

[[11 12 13]
 [13 15 16]
 [11 12 13]
 [13 15 16]]


In [9]:
joined_array_2 = np.concatenate((arrA, arrA), axis = 1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [13 15 16 13 15 16]]


In [15]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [13 15 16]
  [11 12 13]
  [13 15 16]]

 [[11 12 13]
  [13 15 16]
  [11 12 13]
  [13 15 16]]]


In [16]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

#value error: all input arrays must have the same shape

ValueError: all input arrays must have the same shape

In [17]:
another_joined_array = np.concatenate((joined_array_1, arrA))
another_joined_array

array([[11, 12, 13],
       [13, 15, 16],
       [11, 12, 13],
       [13, 15, 16],
       [11, 12, 13],
       [13, 15, 16]])

In [18]:
another_2 = np.concatenate((joined_array_1, arrA), axis = 1)
another_2

#ValueError: It is saying that the dimensions except for the concat axis must match exactly and they do not. 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [19]:
h_stack = np.hstack((arrA, arrA))
h_stack

#stacking along rows

array([[11, 12, 13, 11, 12, 13],
       [13, 15, 16, 13, 15, 16]])

In [20]:
v_stack = np.vstack((arrA, arrA))
v_stack

#stacking along columns

array([[11, 12, 13],
       [13, 15, 16],
       [11, 12, 13],
       [13, 15, 16]])

In [21]:
d_stack = np.dstack((arrA, arrA))
d_stack

#stacking along height/depth

array([[[11, 11],
        [12, 12],
        [13, 13]],

       [[13, 13],
        [15, 15],
        [16, 16]]])

### Splitting Arrays

In [22]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

#splits into 2 arrays with 2 demensions each

[array([[11, 12, 13],
       [13, 15, 16]]), array([[11, 12, 13],
       [13, 15, 16]])]


In [23]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

#splits into 3 arrays with 2 dimensions each

[array([[11, 12, 13],
       [13, 15, 16]]), array([[11, 12, 13]]), array([[13, 15, 16]])]


### Searching and Replacing Array Values

In [24]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
result_1

array([['odd', '12', 'odd'],
       ['odd', 'odd', '16']], dtype='<U21')

### Sorting and Filtering Arrays

In [25]:
arrB = np.array([[7, 6], [13, 5], [7,3]])
arrB

array([[ 7,  6],
       [13,  5],
       [ 7,  3]])

In [26]:
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [27]:
print(arrB)

[[ 7  6]
 [13  5]
 [ 7  3]]


In [28]:
z = arrB < 7
arrC = arrB[z]
print(arrC)

[6 5 3]


In [29]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
