In [1]:
import numpy as np

### Generating Random Numbers 

In [3]:
r_1 = np.random.randint(1, 20, size = (2))
print(r_1)

[18 15]


In [4]:
r_2 = np.random.randint(1, 20, size = (1, 2))
print(r_2)

[[11  5]]


In [8]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.51810314]
 [0.91262742]]


In [9]:
r_4 = np.random.randint(20, 100, size = (4, 5))
print(r_4)

[[55 58 64 74 88]
 [67 47 76 74 93]
 [68 33 52 33 64]
 [78 30 67 79 97]]


In [10]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.77861394 0.03115716 0.16723853 0.57509645 0.63711269]
 [0.48659115 0.94279867 0.48059563 0.5285238  0.33320279]
 [0.50400252 0.33287581 0.55209539 0.96303882 0.30049888]
 [0.77011238 0.39865524 0.16223267 0.63864893 0.20602816]]


### Generating Random Choices from an Array

In [11]:
students =np.array(['Jen', 'Hassan', 'Craig', 'Rodolfo', 'Armando', 'Martin', 'Vanessa', 'Vieri', 'Anthony', 'Aron', 'Kailyn', 'Caitlan'])
students

array(['Jen', 'Hassan', 'Craig', 'Rodolfo', 'Armando', 'Martin',
       'Vanessa', 'Vieri', 'Anthony', 'Aron', 'Kailyn', 'Caitlan'],
      dtype='<U7')

In [12]:
call_on = np.random.choice(students)
print(call_on)

Craig


In [13]:
breakout_groups = np.random.choice((students), size = (3,4))
print(breakout_groups)

#This would not be an effective way to assign breakout groups because it produces duplicate values (Jen is in group 2 three times)

[['Anthony' 'Craig' 'Caitlan' 'Craig']
 ['Jen' 'Jen' 'Martin' 'Jen']
 ['Craig' 'Armando' 'Rodolfo' 'Anthony']]


In [15]:
call_on_weighted = np.random.choice((students), p= [.3, 0.0, 0.07, 0.07, 0.07, .07, .07, .07, .07, .07, .07, .07], size =(5))

#because it was a requirement of assigning a student 0% and another 30%, that left %70 for the remaining 10 students. I equally distributed the remaining equally (7% each). 
print(call_on_weighted)

['Kailyn' 'Kailyn' 'Vieri' 'Jen' 'Caitlan']


### Generating a Normal Distribution

In [16]:
bell_curve = np.random.normal(loc = 10, scale = 5, size = (4,5))
print(bell_curve)

[[ 8.57500106 13.8379865  14.39080018  7.49941633  1.61673326]
 [ 6.22774001 10.13196017 14.02490652  7.6180012  11.25942419]
 [12.0848129  12.37897412  7.3639908  13.49738224 10.60278085]
 [-0.60294685  8.04254982 13.29962469 23.26163002 10.77568203]]
